# Generated by Django 3.2 on 2022-03-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Threads',
            new_name='Thread',
        ),
    ]
