# Generated by Django 3.2 on 2022-03-15 13:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0007_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
