# Generated by Django 3.2 on 2022-03-16 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_thread_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
